packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.29.17
  "@platforma-sdk/ui-vue": ^1.29.17
  "@platforma-sdk/workflow-tengo": ^4.1.2
  "@platforma-sdk/block-tools": ^2.5.38
  "@platforma-sdk/test": ^1.29.20
  "@platforma-sdk/tengo-builder": ^2.1.0
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/eslint-config": ^1.0.3


  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  "@milaboratories/software-pframes-conv": ^2.2.2
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.16
  "@platforma-open/milaboratories.software-mixcr": 4.7.0-148-develop
  "@platforma-open/milaboratories.software-ptransform": ^1.3.1

  "@platforma-open/milaboratories.mixcr-clonotyping-2.model": ^1.9.0

  "vue": ^3.5.12
  "vue-tsc": ^2.1.6

  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.2.3
  "js-yaml": "^4.1.0"

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid


  "vite": ^6.2.3
  "vitest": ^3.0.9
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
