packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.4
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.8.0
  '@platforma-sdk/model': 1.53.11
  '@platforma-sdk/ui-vue': 1.53.11
  '@platforma-sdk/tengo-builder': 2.4.14
  '@platforma-sdk/package-builder': 3.11.0
  '@platforma-sdk/block-tools': 2.6.44
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.53.4
  '@milaboratories/helpers': 1.13.0

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.12
  'typescript': ~5.6.3
  'turbo': ^2.5.4
  'vitest': ^3.0.9
  'shx': ^0.4.0
  'eslint': ^9.25.1
  '@changesets/cli': ^2.27.9

  # Block-specific dependencies
  "@platforma-open/milaboratories.runenv-python-3": 1.4.16
  "@milaboratories/software-pframes-conv": ^2.2.9
  "@platforma-open/milaboratories.software-small-binaries": 1.15.26
  "@platforma-open/milaboratories.software-mixcr": 4.7.0-279-develop
  "@platforma-open/milaboratories.software-ptransform": ^1.6.6
  '@platforma-open/milaboratories.software-repseqio': ^2.5.0-13-master
  "@platforma-open/milaboratories.mixcr-clonotyping-2.model": ^1.9.0
  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid
  '@zip.js/zip.js': ^2.8.2
  '@types/wicg-file-system-access': ^2023.10.6
