packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.48.2
  "@platforma-sdk/ui-vue": ^1.48.8
  "@platforma-sdk/workflow-tengo": ^5.7.3
  "@platforma-sdk/block-tools": ^2.6.25
  "@platforma-sdk/test": ^1.48.8
  "@platforma-sdk/tengo-builder": ^2.4.2
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0


  "@platforma-open/milaboratories.runenv-python-3": 1.4.16
  "@milaboratories/software-pframes-conv": ^2.2.9
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.25
  "@platforma-open/milaboratories.software-mixcr": 4.7.0-254-develop
  "@platforma-open/milaboratories.software-ptransform": ^1.6.6
  '@platforma-open/milaboratories.software-repseqio': ^2.5.0-13-master

  "@platforma-open/milaboratories.mixcr-clonotyping-2.model": ^1.9.0

  '@milaboratories/helpers': ^1.12.1

  "vue": ^3.5.12
  "vue-tsc": ^2.1.6

  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.4

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid


  "vite": ^6.2.3
  "vitest": ^3.0.9
  "@vitejs/plugin-vue": ^5.1.4
  '@zip.js/zip.js': ^2.8.2
  '@types/wicg-file-system-access': ^2023.10.6

  "@changesets/cli": ^2.27.9
